### ISSUE TITLE
Is ethereum implementation (event what is defined in the yellow paper) a moving target?

### ISSUE THREAD

**Issue by diogob** [bkirwi/ethereum-haskell#3]
I'm having some trouble to use the test cases from the ethereum project. I could see on their go implementation (https://github.com/ethereum/go-ethereum/commit/8653db6df0018d08212493e3a3df4677162bdd8f) that MixDigest and SeedHash seem to be 2 new fields in the Block header that are not described in the current version of the Yellow Paper. 

Besides that, in your haskell implementation there is no mention of the logsBloom and receiptsRoot fields, so I took a look at earlier versions of the paper (the ones previous to the last changes in Block.hs) and saw that these fields were also added later on.

So it seems to me that it might be too early for a Haskell implementation. Although I think it is an awesome project, I guess we'll have to wait until the reference implementations are more stable :(

Anyway, thanks for sharing this piece of code, I've learned some things and had a lot of fun with it :D

**Comment by bkirwi** [comment]
Yes, definitely a moving target. Some things aren't changing that quickly -- the RLP / Trie stuff is quite stable -- but other things are getting updated more often. (This code was based mostly off V5 of the yellow paper, so it is indeed a bit stale.)

Glad you've been enjoying it! I do hope that when the Ethereum project settles a bit, most of this code will still be useful. ;)
